### PR TITLE
feat: Implement the overall flow of kubearmor action

### PR DESCRIPTION
**Pull request by zhy76**
Implement the overall flow of kubearmor action

# kubearmor-action
A Github Action used to identify changes in the application posture. Such as what new processes are being spawned and what new file accesses are being made.

## How To Use
```yaml
name: example
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  example_job:
    runs-on: ubuntu-latest
    name: A job to test kubearmor-action
    steps:
      - name: kubearmor-action test
        uses: kubearmor/kubearmor-action@main
        with:
          old-app-image-name: 'nginx:1.22.1' # old app docker image name
          new-app-image-name: 'nginx:1.23' # new app docker image name
          filepath: '/tmp' # file path to store baseline and updated file (default is '/tmp')
```
## Architecture Overview
image

## Result
https://github.com/zhy76/kubearmor-action-demo/actions/runs/5191663971/jobs/9359773680

### CODE REVIEW

**Comment by zhy76** [comment]
> @zhy76 Can you please add vendor directory in gitignore?

OK

**Comment by Ankurk99** [comment]
Hey, why do we have windows based binaries :smile:. Can you please remove them too?

**Comment by zhy76** [comment]
> Hey, why do we have windows based binaries 😄. Can you please remove them too?

Ok, I mainly considered here we can support a variety of different platforms(it does not need now), even in the future we can use [act(run github action locally)](https://github.com/nektos/act) to run the action on the local machine, no need to submit the code to the github action repo, increased project scalability.

**Comment by Ankurk99** [comment]
> Ok, I mainly considered here we can support a variety of different platforms

We can't run KubeArmor on non-linux based systems as we use some important kernel primitives for it to work (eg: LSMs)

**Comment by zhy76** [comment]
> > Ok, I mainly considered here we can support a variety of different platforms
> 
> We can't run KubeArmor on non-linux based systems as we use some important kernel primitives for it to work (eg: LSMs)

OK

**Pull request closed without merging**
